version: '3'

services:
  db:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  api:
    restart: always
    build: ./app
    volumes:
      - ./app:/app
    command: sh -c "uvicorn main:app --reload --port=8000 --host=0.0.0.0"
    env_file:
      - .env 
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./frontend_app
    volumes:
      - ./frontend_app:/app
    command: sh -c "npm run dev"
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API: http://{PUBLIC_IP}:8000
    depends_on:
      - api
      - db
